# Generated by Django 4.1.4 on 2022-12-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50, unique=True)),
                ('max_marks', models.IntegerField()),
                ('date_of_conduction', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('roll_no', models.CharField(max_length=4, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=255)),
                ('hosteler', models.CharField(max_length=255)),
                ('mother_tongue', models.CharField(max_length=255)),
                ('other_languages', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('community', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('educational_qualification', models.CharField(max_length=255)),
                ('name_of_school_last_studied', models.CharField(max_length=1024)),
                ('neet_marks', models.CharField(max_length=255)),
                ('extracurricular_activities', models.CharField(max_length=1024)),
                ('fathers_name', models.CharField(max_length=255)),
                ('fathers_occupation', models.CharField(max_length=255)),
                ('fathers_mobile', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('mothers_occupation', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=1024)),
                ('pincode', models.CharField(max_length=255)),
                ('parents_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalInternalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.student')),
                ('unique_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test', to='users.practicalint')),
            ],
        ),
    ]
