# Generated by Django 4.1.4 on 2023-01-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50, unique=True)),
                ('test_type', models.CharField(max_length=50)),
                ('max_marks', models.PositiveIntegerField()),
                ('date_of_conduction', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='practicalinternalstudent',
            name='s',
        ),
        migrations.RemoveField(
            model_name='practicalinternalstudent',
            name='unique_test',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='PracticalInt',
        ),
        migrations.DeleteModel(
            name='PracticalInternalStudent',
        ),
        migrations.AddField(
            model_name='tests',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.student'),
        ),
        migrations.AddField(
            model_name='tests',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_test', to='users.testtype'),
        ),
    ]
