# Generated by Django 4.1.4 on 2023-01-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetype',
            name='batch_year',
            field=models.CharField(default=2022, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancetype',
            name='duration',
            field=models.IntegerField(default='2022'),
            preserve_default=False,
        ),
    ]
